
version: "3.9"
name: diaster-gateway-dev-core
networks:
  app_net: { driver: bridge }
  idp_net: { driver: bridge }

services:
  camel-api:
    build:
      context: ../
      dockerfile: docker/camel-api/Dockerfile
    container_name: dg-dev-camel-core
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - ../env/.env.dev
    ports:
      - "${SERVER_PORT:-8088}:8088"
    volumes:
      - ../api/src/main/resources/inbox:/opt/app/inbox
      - ./logs:/opt/app/logs
    #depends_on:
      #app-postgres: { condition: service_healthy }
      #keycloak: { condition: service_started }
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://localhost:8088/actuator/health | grep -q '\"status\":\"UP\"' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 30
    networks: [app_net, idp_net]
